pipelines:
  build:
    group: default
    label_template: "app-frontend-${COUNT}"
    materials:
      source_code:
        git: "git@git.thoughtworks.net:bookstore/bookstore-frontend.git"
        branch: master
    stages:
      - build:
          jobs:
            pre_build:
              tasks:
                - exec:
                  run_if: any
                  command: sh
                  arguments:
                    - pipeline-scripts/pre_build.sh
