pipelines:
  build:
    group: frontend
    materials:
      source_code:
        git: "git@github.com:lazurey/gocd-tmpl.git"
        branch: master
    stages:
      - test:
          jobs:
            pre_build:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - 'test test test'
      - build:
          jobs:
            pre_build:
              tasks:
                - script: ./pipeline-scripts/pre_build.sh
