pipelines:
  build:
    group: frontend
    materials:
      source_code:
        git: "git@git.thoughtworks.net:bookstore/bookstore-frontend.git"
        branch: master
    stages:
      - pre_build:
          jobs:
            pre_build:
              tasks:
                - script: ./pipeline-scripts/pre_build.sh
